---
title: "An Analysis on Nonresponse Rates in Web Surveys"
author: Catherine Punnoose
thanks: "Code and data are available at: https://github.com/catherinee1216/Tutorial_8.git"
date: today
date-format: long
format: pdf
number-sections: true
bibliography: references.bib
---

# Introduction 

The article, *Special Virtual Issue on Nonresponse Rates and Nonresponse Adjustments* sheds light on various challenges associated with nonresponse rates in survey administration. One highlighted concern is the diminishing response rates in surveys, particularly evident in the realm of web surveys.

The article briefly touches upon the observed decline in responses to web surveys, acknowledged as the most effective and efficient means of gathering data across a broad sample population. A comparison of response rates across various survey types indicates that online surveys stand out as the most time and cost-efficient method for sample populations exceeding 300 [@SD]. Online surveys offer several advantages, including reduced research costs, quicker implementation, decreased transcription errors, and simplified analysis [@SD].

Despite being the preferred method for large-scale data collection, web surveys exhibit a notably high nonresponse rate. As the article notes, "the downward trend in response rates appears across modes, and the shift to web surveys is accelerating an industry-wide response rate decline" [@citeSurvey]. Additional studies suggest that nonresponse rates on web surveys are approximately 12 percent higher compared to alternative survey methods [@SageJ]. 

Referring to Jessica Daikeler, Michael Bošnjak, and Katja Lozar Manfreda's study, "Web Versus Other Survey Modes: An Updated and Extended Meta-Analysis Comparing Response Rates," the article cites a 12 percent lower response rate in online surveys compared to modes such as mail, email, telephone, and in-person surveys [@SD]. Hence, proving that there is a significant decrease in response rates for web surveys. 

Using the open-source statistical programming language R [@citeR], this short paper will briefly analyze possible causes for low response rates in web surveys as well as methods to improve response rates. 



# Possible Causes for Low Response Rate 

Acknowledging the surprisingly low response rates in web surveys, several factors may account for this phenomenon. One factor is the misconception that a larger sample size ensures a higher response rate. Contrary to this belief, the average response rate for online surveys stands at 44.1% [@SD]. 

A study by Gregor Čehovin et al. (2022) found that sending surveys to more participants did not necessarily result in a heightened response rate [@SageJ]. Instead, the study recommends targeting a clearly defined and refined population to enhance response rates [@SD]. Furthermore, the research indicates that surveys sent to smaller sample sizes reported higher response rates [@SD]. Hence it is suggested that further studies target smaller sample sizes to have a positive response rate. 

# Improving Web Survey Response Rates 

To improve response rates in web surveys Gregor Čehovin et al. (2022) provide the following recommendations to consider [@SageJ]: 

* The average response rate of an online survey in the education-related field is 44%
* Sending surveys to more participants does not necessarily yield a higher response rate. It is more critical to have a clearly defined and refined population to send the surveys to.
* When planning an online survey, consider: 
    + pre-contact the potential participants
    + use other types of surveys in conjunction with online surveys
    + use phone calls to remind the participants about the survey
* Incentives do not guarantee a boost in the online survey response rates

Applying such recommendations may help improve response rates of further web surveys. 


\newpage


# References


